import type { Metadata } from "next";
// import Image from "next/image";
// import styles from "./page.module.css";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./header/page";
import MarketStatus from "./components/MarketStatus";
import StockPrice from "./components/StockPrice";
// import AutoComplete from "./components/AutoComplete";
import AutoCompletex from "./components/AutoCompletex";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* <div style={{ display: 'flex', flexDirection: 'column' }}> */}
          <div style={{ position: 'sticky', top: 0, zIndex: 100 }}>
            <Header />
            <div style={{ display: 'flex', justifyContent: 'flex-end', padding: '8px 5%', gap: '16px' }}>
              <StockPrice instrumentKey="NSE_INDEX|Nifty 50" />
              <MarketStatus />
              {/* <AutoComplete /> */}
              <AutoCompletex />
            </div>
          </div>
          <div style={{margin: '16px 5%', width: '90%'}}>
            {children}
          </div>
        {/* </div> */}
      </body>
    </html>
  );
}
